// GENERATED FILE — DO NOT EDIT.
//
// The 15 flyable Elite-A hulls: lasers, mounts, armour and flight envelope.
//
// Written by `npm run generate:elite-a` from the vendored pack under
// reference/elite-a/source. To change it, change the importer or the pack,
// regenerate, and review the diff. `npm run generate:elite-a -- --check`
// fails if this file and the pack have drifted apart.
//
// source-hash: 85fece5618c1302dac6b2bbc5c6e78629d37fb5ac27769dddf24fb0b38b52ccb

import type { EliteAPlayerHull } from './types.ts';

export const ELITE_A_PLAYER_HULLS: readonly EliteAPlayerHull[] = [
  { playerShipId: 0, name: "Adder", lasers: { pulse: { rawByte: 14, continuousFlag: false, power: 14, baseDamagePerHit: 7 }, beam: { rawByte: 142, continuousFlag: true, power: 14, baseDamagePerHit: 7 }, military: { rawByte: 146, continuousFlag: true, power: 18, baseDamagePerHit: 9 }, mining: { rawByte: 25, continuousFlag: false, power: 25, baseDamagePerHit: 12 } }, laserMounts: 2, laserMountDescription: "front and rear", maxMissiles: 1, perHitShieldArmour: 4, energyRechargeRating: 1, maxSpeed: 36, cargoHoldCapacity: 8, hyperspaceRangeLightYears: 6, equipmentPriceGroup: 1, maxPitchRollRate: 223, minPitchRollRate: 33, frontShieldCapacity: 255, aftShieldCapacity: 255, energyBankCapacity: 255 },
  { playerShipId: 1, name: "Gecko", lasers: { pulse: { rawByte: 14, continuousFlag: false, power: 14, baseDamagePerHit: 7 }, beam: { rawByte: 143, continuousFlag: true, power: 15, baseDamagePerHit: 7 }, military: { rawByte: 147, continuousFlag: true, power: 19, baseDamagePerHit: 9 }, mining: { rawByte: 25, continuousFlag: false, power: 25, baseDamagePerHit: 12 } }, laserMounts: 4, laserMountDescription: "front, rear, left and right", maxMissiles: 2, perHitShieldArmour: 5, energyRechargeRating: 1, maxSpeed: 45, cargoHoldCapacity: 9, hyperspaceRangeLightYears: 7, equipmentPriceGroup: 1, maxPitchRollRate: 239, minPitchRollRate: 17, frontShieldCapacity: 255, aftShieldCapacity: 255, energyBankCapacity: 255 },
  { playerShipId: 2, name: "Moray", lasers: { pulse: { rawByte: 16, continuousFlag: false, power: 16, baseDamagePerHit: 8 }, beam: { rawByte: 143, continuousFlag: true, power: 15, baseDamagePerHit: 7 }, military: { rawByte: 150, continuousFlag: true, power: 22, baseDamagePerHit: 11 }, mining: { rawByte: 25, continuousFlag: false, power: 25, baseDamagePerHit: 12 } }, laserMounts: 4, laserMountDescription: "front, rear, left and right", maxMissiles: 2, perHitShieldArmour: 6, energyRechargeRating: 1, maxSpeed: 38, cargoHoldCapacity: 11, hyperspaceRangeLightYears: 8, equipmentPriceGroup: 4, maxPitchRollRate: 239, minPitchRollRate: 17, frontShieldCapacity: 255, aftShieldCapacity: 255, energyBankCapacity: 255 },
  { playerShipId: 3, name: "Cobra Mk I", lasers: { pulse: { rawByte: 14, continuousFlag: false, power: 14, baseDamagePerHit: 7 }, beam: { rawByte: 142, continuousFlag: true, power: 14, baseDamagePerHit: 7 }, military: { rawByte: 148, continuousFlag: true, power: 20, baseDamagePerHit: 10 }, mining: { rawByte: 25, continuousFlag: false, power: 25, baseDamagePerHit: 12 } }, laserMounts: 4, laserMountDescription: "front, rear, left and right", maxMissiles: 3, perHitShieldArmour: 5, energyRechargeRating: 1, maxSpeed: 39, cargoHoldCapacity: 14, hyperspaceRangeLightYears: 6, equipmentPriceGroup: 1, maxPitchRollRate: 207, minPitchRollRate: 49, frontShieldCapacity: 255, aftShieldCapacity: 255, energyBankCapacity: 255 },
  { playerShipId: 4, name: "Iguana", lasers: { pulse: { rawByte: 14, continuousFlag: false, power: 14, baseDamagePerHit: 7 }, beam: { rawByte: 142, continuousFlag: true, power: 14, baseDamagePerHit: 7 }, military: { rawByte: 148, continuousFlag: true, power: 20, baseDamagePerHit: 10 }, mining: { rawByte: 25, continuousFlag: false, power: 25, baseDamagePerHit: 12 } }, laserMounts: 4, laserMountDescription: "front, rear, left and right", maxMissiles: 3, perHitShieldArmour: 7, energyRechargeRating: 1, maxSpeed: 50, cargoHoldCapacity: 21, hyperspaceRangeLightYears: 7.5, equipmentPriceGroup: 0, maxPitchRollRate: 223, minPitchRollRate: 33, frontShieldCapacity: 255, aftShieldCapacity: 255, energyBankCapacity: 255 },
  { playerShipId: 5, name: "Ophidian", lasers: { pulse: { rawByte: 13, continuousFlag: false, power: 13, baseDamagePerHit: 6 }, beam: { rawByte: 141, continuousFlag: true, power: 13, baseDamagePerHit: 6 }, military: { rawByte: 144, continuousFlag: true, power: 16, baseDamagePerHit: 8 }, mining: { rawByte: 12, continuousFlag: false, power: 12, baseDamagePerHit: 6 } }, laserMounts: 1, laserMountDescription: "front", maxMissiles: 2, perHitShieldArmour: 4, energyRechargeRating: 1, maxSpeed: 51, cargoHoldCapacity: 24, hyperspaceRangeLightYears: 7, equipmentPriceGroup: 4, maxPitchRollRate: 255, minPitchRollRate: 1, frontShieldCapacity: 255, aftShieldCapacity: 255, energyBankCapacity: 255 },
  { playerShipId: 6, name: "Chameleon", lasers: { pulse: { rawByte: 16, continuousFlag: false, power: 16, baseDamagePerHit: 8 }, beam: { rawByte: 143, continuousFlag: true, power: 15, baseDamagePerHit: 7 }, military: { rawByte: 151, continuousFlag: true, power: 23, baseDamagePerHit: 11 }, mining: { rawByte: 50, continuousFlag: false, power: 50, baseDamagePerHit: 25 } }, laserMounts: 2, laserMountDescription: "front and rear", maxMissiles: 3, perHitShieldArmour: 8, energyRechargeRating: 1, maxSpeed: 43, cargoHoldCapacity: 35, hyperspaceRangeLightYears: 8, equipmentPriceGroup: 4, maxPitchRollRate: 223, minPitchRollRate: 33, frontShieldCapacity: 255, aftShieldCapacity: 255, energyBankCapacity: 255 },
  { playerShipId: 7, name: "Cobra Mk III", lasers: { pulse: { rawByte: 18, continuousFlag: false, power: 18, baseDamagePerHit: 9 }, beam: { rawByte: 143, continuousFlag: true, power: 15, baseDamagePerHit: 7 }, military: { rawByte: 152, continuousFlag: true, power: 24, baseDamagePerHit: 12 }, mining: { rawByte: 50, continuousFlag: false, power: 50, baseDamagePerHit: 25 } }, laserMounts: 4, laserMountDescription: "front, rear, left and right", maxMissiles: 4, perHitShieldArmour: 7, energyRechargeRating: 1, maxSpeed: 42, cargoHoldCapacity: 42, hyperspaceRangeLightYears: 7, equipmentPriceGroup: 0, maxPitchRollRate: 239, minPitchRollRate: 17, frontShieldCapacity: 255, aftShieldCapacity: 255, energyBankCapacity: 255 },
  { playerShipId: 8, name: "Fer-de-Lance", lasers: { pulse: { rawByte: 18, continuousFlag: false, power: 18, baseDamagePerHit: 9 }, beam: { rawByte: 146, continuousFlag: true, power: 18, baseDamagePerHit: 9 }, military: { rawByte: 156, continuousFlag: true, power: 28, baseDamagePerHit: 14 }, mining: { rawByte: 50, continuousFlag: false, power: 50, baseDamagePerHit: 25 } }, laserMounts: 4, laserMountDescription: "front, rear, left and right", maxMissiles: 3, perHitShieldArmour: 8, energyRechargeRating: 2, maxSpeed: 45, cargoHoldCapacity: 9, hyperspaceRangeLightYears: 8.5, equipmentPriceGroup: 2, maxPitchRollRate: 223, minPitchRollRate: 33, frontShieldCapacity: 255, aftShieldCapacity: 255, energyBankCapacity: 255 },
  { playerShipId: 9, name: "Ghavial", lasers: { pulse: { rawByte: 17, continuousFlag: false, power: 17, baseDamagePerHit: 8 }, beam: { rawByte: 144, continuousFlag: true, power: 16, baseDamagePerHit: 8 }, military: { rawByte: 153, continuousFlag: true, power: 25, baseDamagePerHit: 12 }, mining: { rawByte: 50, continuousFlag: false, power: 50, baseDamagePerHit: 25 } }, laserMounts: 4, laserMountDescription: "front, rear, left and right", maxMissiles: 3, perHitShieldArmour: 9, energyRechargeRating: 1, maxSpeed: 37, cargoHoldCapacity: 55, hyperspaceRangeLightYears: 8, equipmentPriceGroup: 0, maxPitchRollRate: 207, minPitchRollRate: 49, frontShieldCapacity: 255, aftShieldCapacity: 255, energyBankCapacity: 255 },
  { playerShipId: 10, name: "Monitor", lasers: { pulse: { rawByte: 24, continuousFlag: false, power: 24, baseDamagePerHit: 12 }, beam: { rawByte: 147, continuousFlag: true, power: 19, baseDamagePerHit: 9 }, military: { rawByte: 156, continuousFlag: true, power: 28, baseDamagePerHit: 14 }, mining: { rawByte: 50, continuousFlag: false, power: 50, baseDamagePerHit: 25 } }, laserMounts: 4, laserMountDescription: "front, rear, left and right", maxMissiles: 8, perHitShieldArmour: 10, energyRechargeRating: 1, maxSpeed: 24, cargoHoldCapacity: 81, hyperspaceRangeLightYears: 11, equipmentPriceGroup: 3, maxPitchRollRate: 191, minPitchRollRate: 65, frontShieldCapacity: 255, aftShieldCapacity: 255, energyBankCapacity: 255 },
  { playerShipId: 11, name: "Python", lasers: { pulse: { rawByte: 24, continuousFlag: false, power: 24, baseDamagePerHit: 12 }, beam: { rawByte: 146, continuousFlag: true, power: 18, baseDamagePerHit: 9 }, military: { rawByte: 155, continuousFlag: true, power: 27, baseDamagePerHit: 13 }, mining: { rawByte: 50, continuousFlag: false, power: 50, baseDamagePerHit: 25 } }, laserMounts: 4, laserMountDescription: "front, rear, left and right", maxMissiles: 4, perHitShieldArmour: 11, energyRechargeRating: 1, maxSpeed: 30, cargoHoldCapacity: 106, hyperspaceRangeLightYears: 8, equipmentPriceGroup: 1, maxPitchRollRate: 175, minPitchRollRate: 81, frontShieldCapacity: 255, aftShieldCapacity: 255, energyBankCapacity: 255 },
  { playerShipId: 12, name: "Boa", lasers: { pulse: { rawByte: 20, continuousFlag: false, power: 20, baseDamagePerHit: 10 }, beam: { rawByte: 142, continuousFlag: true, power: 14, baseDamagePerHit: 7 }, military: { rawByte: 152, continuousFlag: true, power: 24, baseDamagePerHit: 12 }, mining: { rawByte: 50, continuousFlag: false, power: 50, baseDamagePerHit: 25 } }, laserMounts: 2, laserMountDescription: "front and rear", maxMissiles: 6, perHitShieldArmour: 10, energyRechargeRating: 1, maxSpeed: 36, cargoHoldCapacity: 132, hyperspaceRangeLightYears: 9, equipmentPriceGroup: 0, maxPitchRollRate: 191, minPitchRollRate: 65, frontShieldCapacity: 255, aftShieldCapacity: 255, energyBankCapacity: 255 },
  { playerShipId: 13, name: "Asp Mk II", lasers: { pulse: { rawByte: 16, continuousFlag: false, power: 16, baseDamagePerHit: 8 }, beam: { rawByte: 145, continuousFlag: true, power: 17, baseDamagePerHit: 8 }, military: { rawByte: 159, continuousFlag: true, power: 31, baseDamagePerHit: 15 }, mining: { rawByte: 12, continuousFlag: false, power: 12, baseDamagePerHit: 6 } }, laserMounts: 1, laserMountDescription: "front", maxMissiles: 1, perHitShieldArmour: 10, energyRechargeRating: 1, maxSpeed: 60, cargoHoldCapacity: 6, hyperspaceRangeLightYears: 12.5, equipmentPriceGroup: 2, maxPitchRollRate: 223, minPitchRollRate: 33, frontShieldCapacity: 255, aftShieldCapacity: 255, energyBankCapacity: 255 },
  { playerShipId: 14, name: "Anaconda", lasers: { pulse: { rawByte: 28, continuousFlag: false, power: 28, baseDamagePerHit: 14 }, beam: { rawByte: 144, continuousFlag: true, power: 16, baseDamagePerHit: 8 }, military: { rawByte: 127, continuousFlag: false, power: 127, baseDamagePerHit: 63 }, mining: { rawByte: 50, continuousFlag: false, power: 50, baseDamagePerHit: 25 } }, laserMounts: 4, laserMountDescription: "front, rear, left and right", maxMissiles: 16, perHitShieldArmour: 13, energyRechargeRating: 1, maxSpeed: 21, cargoHoldCapacity: 253, hyperspaceRangeLightYears: 10, equipmentPriceGroup: 3, maxPitchRollRate: 175, minPitchRollRate: 81, frontShieldCapacity: 255, aftShieldCapacity: 255, energyBankCapacity: 255 },
];
