// GENERATED FILE — DO NOT EDIT.
//
// The 713 blueprint-slot assignments: which design fills which role in which
// set, with its raw NEWB byte.
//
// Written by `npm run generate:elite-a` from the vendored pack under
// reference/elite-a/source. To change it, change the importer or the pack,
// regenerate, and review the diff. `npm run generate:elite-a -- --check`
// fails if this file and the pack have drifted apart.
//
// source-hash: 85fece5618c1302dac6b2bbc5c6e78629d37fb5ac27769dddf24fb0b38b52ccb

import type { EliteASlot } from './types.ts';

export const ELITE_A_SLOTS: readonly EliteASlot[] = [
  { blueprintSet: "A", slot: 1, slotCategory: "missile", designId: 15, shipSymbol: "SHIP_MISSILE", newbRaw: 0 },
  { blueprintSet: "A", slot: 2, slotCategory: "station", designId: 1, shipSymbol: "SHIP_CORIOLIS", newbRaw: 64 },
  { blueprintSet: "A", slot: 3, slotCategory: "escape pod", designId: 2, shipSymbol: "SHIP_ESCAPE_POD", newbRaw: 65 },
  { blueprintSet: "A", slot: 4, slotCategory: "cargo", designId: 3, shipSymbol: "SHIP_PLATE", newbRaw: 0 },
  { blueprintSet: "A", slot: 5, slotCategory: "cargo", designId: 4, shipSymbol: "SHIP_CANISTER", newbRaw: 0 },
  { blueprintSet: "A", slot: 6, slotCategory: "mining", designId: 5, shipSymbol: "SHIP_BOULDER", newbRaw: 0 },
  { blueprintSet: "A", slot: 7, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "A", slot: 8, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "A", slot: 9, slotCategory: "shuttle", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "A", slot: 10, slotCategory: "transporter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "A", slot: 11, slotCategory: "trader", designId: 30, shipSymbol: "SHIP_MONITOR", newbRaw: 160 },
  { blueprintSet: "A", slot: 12, slotCategory: "trader", designId: 20, shipSymbol: "SHIP_ADDER", newbRaw: 161 },
  { blueprintSet: "A", slot: 13, slotCategory: "trader", designId: 22, shipSymbol: "SHIP_COBRA_MK_1", newbRaw: 160 },
  { blueprintSet: "A", slot: 14, slotCategory: "trader / large carrier", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "A", slot: 15, slotCategory: "small child ship", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "A", slot: 16, slotCategory: "cop", designId: 16, shipSymbol: "SHIP_VIPER", newbRaw: 194 },
  { blueprintSet: "A", slot: 17, slotCategory: "pirate", designId: 22, shipSymbol: "SHIP_COBRA_MK_1", newbRaw: 140 },
  { blueprintSet: "A", slot: 18, slotCategory: "pirate", designId: 21, shipSymbol: "SHIP_GECKO", newbRaw: 140 },
  { blueprintSet: "A", slot: 19, slotCategory: "pirate", designId: 20, shipSymbol: "SHIP_ADDER", newbRaw: 132 },
  { blueprintSet: "A", slot: 20, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "A", slot: 21, slotCategory: "pirate", designId: 31, shipSymbol: "SHIP_OPHIDIAN", newbRaw: 132 },
  { blueprintSet: "A", slot: 22, slotCategory: "pirate", designId: 25, shipSymbol: "SHIP_MORAY", newbRaw: 140 },
  { blueprintSet: "A", slot: 23, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "A", slot: 24, slotCategory: "pirate", designId: 30, shipSymbol: "SHIP_MONITOR", newbRaw: 140 },
  { blueprintSet: "A", slot: 25, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "A", slot: 26, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "A", slot: 27, slotCategory: "bounty hunter", designId: 20, shipSymbol: "SHIP_ADDER", newbRaw: 130 },
  { blueprintSet: "A", slot: 28, slotCategory: "bounty hunter", designId: 30, shipSymbol: "SHIP_MONITOR", newbRaw: 162 },
  { blueprintSet: "A", slot: 29, slotCategory: "Thargoid", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "A", slot: 30, slotCategory: "Thargon", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "A", slot: 31, slotCategory: "Constrictor", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "B", slot: 1, slotCategory: "missile", designId: 15, shipSymbol: "SHIP_MISSILE", newbRaw: 0 },
  { blueprintSet: "B", slot: 2, slotCategory: "station", designId: 0, shipSymbol: "SHIP_DODO", newbRaw: 64 },
  { blueprintSet: "B", slot: 3, slotCategory: "escape pod", designId: 2, shipSymbol: "SHIP_ESCAPE_POD", newbRaw: 65 },
  { blueprintSet: "B", slot: 4, slotCategory: "cargo", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "B", slot: 5, slotCategory: "cargo", designId: 4, shipSymbol: "SHIP_CANISTER", newbRaw: 0 },
  { blueprintSet: "B", slot: 6, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "B", slot: 7, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "B", slot: 8, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "B", slot: 9, slotCategory: "shuttle", designId: 36, shipSymbol: "SHIP_SHUTTLE_MK_2", newbRaw: 33 },
  { blueprintSet: "B", slot: 10, slotCategory: "transporter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "B", slot: 11, slotCategory: "trader", designId: 32, shipSymbol: "SHIP_GHAVIAL", newbRaw: 160 },
  { blueprintSet: "B", slot: 12, slotCategory: "trader", designId: 30, shipSymbol: "SHIP_MONITOR", newbRaw: 161 },
  { blueprintSet: "B", slot: 13, slotCategory: "trader", designId: 22, shipSymbol: "SHIP_COBRA_MK_1", newbRaw: 160 },
  { blueprintSet: "B", slot: 14, slotCategory: "trader / large carrier", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "B", slot: 15, slotCategory: "small child ship", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "B", slot: 16, slotCategory: "cop", designId: 16, shipSymbol: "SHIP_VIPER", newbRaw: 194 },
  { blueprintSet: "B", slot: 17, slotCategory: "pirate", designId: 22, shipSymbol: "SHIP_COBRA_MK_1", newbRaw: 140 },
  { blueprintSet: "B", slot: 18, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "B", slot: 19, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "B", slot: 20, slotCategory: "pirate", designId: 35, shipSymbol: "SHIP_IGUANA", newbRaw: 140 },
  { blueprintSet: "B", slot: 21, slotCategory: "pirate", designId: 10, shipSymbol: "SHIP_COBRA_MK_3", newbRaw: 132 },
  { blueprintSet: "B", slot: 22, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "B", slot: 23, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "B", slot: 24, slotCategory: "pirate", designId: 30, shipSymbol: "SHIP_MONITOR", newbRaw: 140 },
  { blueprintSet: "B", slot: 25, slotCategory: "bounty hunter", designId: 10, shipSymbol: "SHIP_COBRA_MK_3", newbRaw: 130 },
  { blueprintSet: "B", slot: 26, slotCategory: "bounty hunter", designId: 35, shipSymbol: "SHIP_IGUANA", newbRaw: 162 },
  { blueprintSet: "B", slot: 27, slotCategory: "bounty hunter", designId: 22, shipSymbol: "SHIP_COBRA_MK_1", newbRaw: 130 },
  { blueprintSet: "B", slot: 28, slotCategory: "bounty hunter", designId: 32, shipSymbol: "SHIP_GHAVIAL", newbRaw: 162 },
  { blueprintSet: "B", slot: 29, slotCategory: "Thargoid", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "B", slot: 30, slotCategory: "Thargon", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "B", slot: 31, slotCategory: "Constrictor", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "C", slot: 1, slotCategory: "missile", designId: 15, shipSymbol: "SHIP_MISSILE", newbRaw: 0 },
  { blueprintSet: "C", slot: 2, slotCategory: "station", designId: 1, shipSymbol: "SHIP_CORIOLIS", newbRaw: 64 },
  { blueprintSet: "C", slot: 3, slotCategory: "escape pod", designId: 2, shipSymbol: "SHIP_ESCAPE_POD", newbRaw: 65 },
  { blueprintSet: "C", slot: 4, slotCategory: "cargo", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "C", slot: 5, slotCategory: "cargo", designId: 4, shipSymbol: "SHIP_CANISTER", newbRaw: 0 },
  { blueprintSet: "C", slot: 6, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "C", slot: 7, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "C", slot: 8, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "C", slot: 9, slotCategory: "shuttle", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "C", slot: 10, slotCategory: "transporter", designId: 9, shipSymbol: "SHIP_TRANSPORTER", newbRaw: 97 },
  { blueprintSet: "C", slot: 11, slotCategory: "trader", designId: 11, shipSymbol: "SHIP_PYTHON", newbRaw: 160 },
  { blueprintSet: "C", slot: 12, slotCategory: "trader", designId: 34, shipSymbol: "SHIP_RATTLER", newbRaw: 161 },
  { blueprintSet: "C", slot: 13, slotCategory: "trader", designId: 37, shipSymbol: "SHIP_CHAMELEON", newbRaw: 160 },
  { blueprintSet: "C", slot: 14, slotCategory: "trader / large carrier", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "C", slot: 15, slotCategory: "small child ship", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "C", slot: 16, slotCategory: "cop", designId: 16, shipSymbol: "SHIP_VIPER", newbRaw: 194 },
  { blueprintSet: "C", slot: 17, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "C", slot: 18, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "C", slot: 19, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "C", slot: 20, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "C", slot: 21, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "C", slot: 22, slotCategory: "pirate", designId: 34, shipSymbol: "SHIP_RATTLER", newbRaw: 140 },
  { blueprintSet: "C", slot: 23, slotCategory: "pirate", designId: 37, shipSymbol: "SHIP_CHAMELEON", newbRaw: 132 },
  { blueprintSet: "C", slot: 24, slotCategory: "pirate", designId: 11, shipSymbol: "SHIP_PYTHON", newbRaw: 140 },
  { blueprintSet: "C", slot: 25, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "C", slot: 26, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "C", slot: 27, slotCategory: "bounty hunter", designId: 11, shipSymbol: "SHIP_PYTHON", newbRaw: 130 },
  { blueprintSet: "C", slot: 28, slotCategory: "bounty hunter", designId: 34, shipSymbol: "SHIP_RATTLER", newbRaw: 162 },
  { blueprintSet: "C", slot: 29, slotCategory: "Thargoid", designId: 26, shipSymbol: "SHIP_THARGOID", newbRaw: 12 },
  { blueprintSet: "C", slot: 30, slotCategory: "Thargon", designId: 27, shipSymbol: "SHIP_THARGON", newbRaw: 4 },
  { blueprintSet: "C", slot: 31, slotCategory: "Constrictor", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "D", slot: 1, slotCategory: "missile", designId: 15, shipSymbol: "SHIP_MISSILE", newbRaw: 0 },
  { blueprintSet: "D", slot: 2, slotCategory: "station", designId: 0, shipSymbol: "SHIP_DODO", newbRaw: 64 },
  { blueprintSet: "D", slot: 3, slotCategory: "escape pod", designId: 2, shipSymbol: "SHIP_ESCAPE_POD", newbRaw: 65 },
  { blueprintSet: "D", slot: 4, slotCategory: "cargo", designId: 3, shipSymbol: "SHIP_PLATE", newbRaw: 0 },
  { blueprintSet: "D", slot: 5, slotCategory: "cargo", designId: 4, shipSymbol: "SHIP_CANISTER", newbRaw: 0 },
  { blueprintSet: "D", slot: 6, slotCategory: "mining", designId: 5, shipSymbol: "SHIP_BOULDER", newbRaw: 0 },
  { blueprintSet: "D", slot: 7, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "D", slot: 8, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "D", slot: 9, slotCategory: "shuttle", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "D", slot: 10, slotCategory: "transporter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "D", slot: 11, slotCategory: "trader", designId: 12, shipSymbol: "SHIP_BOA", newbRaw: 160 },
  { blueprintSet: "D", slot: 12, slotCategory: "trader", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "D", slot: 13, slotCategory: "trader", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "D", slot: 14, slotCategory: "trader / large carrier", designId: 29, shipSymbol: "SHIP_DRAGON", newbRaw: 33 },
  { blueprintSet: "D", slot: 15, slotCategory: "small child ship", designId: 17, shipSymbol: "SHIP_SIDEWINDER", newbRaw: 12 },
  { blueprintSet: "D", slot: 16, slotCategory: "cop", designId: 16, shipSymbol: "SHIP_VIPER", newbRaw: 194 },
  { blueprintSet: "D", slot: 17, slotCategory: "pirate", designId: 17, shipSymbol: "SHIP_SIDEWINDER", newbRaw: 12 },
  { blueprintSet: "D", slot: 18, slotCategory: "pirate", designId: 17, shipSymbol: "SHIP_SIDEWINDER", newbRaw: 12 },
  { blueprintSet: "D", slot: 19, slotCategory: "pirate", designId: 21, shipSymbol: "SHIP_GECKO", newbRaw: 132 },
  { blueprintSet: "D", slot: 20, slotCategory: "pirate", designId: 33, shipSymbol: "SHIP_BUSHMASTER", newbRaw: 140 },
  { blueprintSet: "D", slot: 21, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "D", slot: 22, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "D", slot: 23, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "D", slot: 24, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "D", slot: 25, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "D", slot: 26, slotCategory: "bounty hunter", designId: 33, shipSymbol: "SHIP_BUSHMASTER", newbRaw: 162 },
  { blueprintSet: "D", slot: 27, slotCategory: "bounty hunter", designId: 21, shipSymbol: "SHIP_GECKO", newbRaw: 130 },
  { blueprintSet: "D", slot: 28, slotCategory: "bounty hunter", designId: 17, shipSymbol: "SHIP_SIDEWINDER", newbRaw: 34 },
  { blueprintSet: "D", slot: 29, slotCategory: "Thargoid", designId: 26, shipSymbol: "SHIP_THARGOID", newbRaw: 12 },
  { blueprintSet: "D", slot: 30, slotCategory: "Thargon", designId: 27, shipSymbol: "SHIP_THARGON", newbRaw: 4 },
  { blueprintSet: "D", slot: 31, slotCategory: "Constrictor", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "E", slot: 1, slotCategory: "missile", designId: 15, shipSymbol: "SHIP_MISSILE", newbRaw: 0 },
  { blueprintSet: "E", slot: 2, slotCategory: "station", designId: 1, shipSymbol: "SHIP_CORIOLIS", newbRaw: 64 },
  { blueprintSet: "E", slot: 3, slotCategory: "escape pod", designId: 2, shipSymbol: "SHIP_ESCAPE_POD", newbRaw: 65 },
  { blueprintSet: "E", slot: 4, slotCategory: "cargo", designId: 3, shipSymbol: "SHIP_PLATE", newbRaw: 0 },
  { blueprintSet: "E", slot: 5, slotCategory: "cargo", designId: 4, shipSymbol: "SHIP_CANISTER", newbRaw: 0 },
  { blueprintSet: "E", slot: 6, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "E", slot: 7, slotCategory: "mining", designId: 6, shipSymbol: "SHIP_ASTEROID", newbRaw: 0 },
  { blueprintSet: "E", slot: 8, slotCategory: "mining", designId: 7, shipSymbol: "SHIP_SPLINTER", newbRaw: 0 },
  { blueprintSet: "E", slot: 9, slotCategory: "shuttle", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "E", slot: 10, slotCategory: "transporter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "E", slot: 11, slotCategory: "trader", designId: 11, shipSymbol: "SHIP_PYTHON", newbRaw: 160 },
  { blueprintSet: "E", slot: 12, slotCategory: "trader", designId: 34, shipSymbol: "SHIP_RATTLER", newbRaw: 161 },
  { blueprintSet: "E", slot: 13, slotCategory: "trader", designId: 35, shipSymbol: "SHIP_IGUANA", newbRaw: 160 },
  { blueprintSet: "E", slot: 14, slotCategory: "trader / large carrier", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "E", slot: 15, slotCategory: "small child ship", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "E", slot: 16, slotCategory: "cop", designId: 16, shipSymbol: "SHIP_VIPER", newbRaw: 194 },
  { blueprintSet: "E", slot: 17, slotCategory: "pirate", designId: 21, shipSymbol: "SHIP_GECKO", newbRaw: 140 },
  { blueprintSet: "E", slot: 18, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "E", slot: 19, slotCategory: "pirate", designId: 20, shipSymbol: "SHIP_ADDER", newbRaw: 132 },
  { blueprintSet: "E", slot: 20, slotCategory: "pirate", designId: 35, shipSymbol: "SHIP_IGUANA", newbRaw: 140 },
  { blueprintSet: "E", slot: 21, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "E", slot: 22, slotCategory: "pirate", designId: 11, shipSymbol: "SHIP_PYTHON", newbRaw: 140 },
  { blueprintSet: "E", slot: 23, slotCategory: "pirate", designId: 34, shipSymbol: "SHIP_RATTLER", newbRaw: 132 },
  { blueprintSet: "E", slot: 24, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "E", slot: 25, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "E", slot: 26, slotCategory: "bounty hunter", designId: 35, shipSymbol: "SHIP_IGUANA", newbRaw: 162 },
  { blueprintSet: "E", slot: 27, slotCategory: "bounty hunter", designId: 11, shipSymbol: "SHIP_PYTHON", newbRaw: 130 },
  { blueprintSet: "E", slot: 28, slotCategory: "bounty hunter", designId: 21, shipSymbol: "SHIP_GECKO", newbRaw: 162 },
  { blueprintSet: "E", slot: 29, slotCategory: "Thargoid", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "E", slot: 30, slotCategory: "Thargon", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "E", slot: 31, slotCategory: "Constrictor", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "F", slot: 1, slotCategory: "missile", designId: 15, shipSymbol: "SHIP_MISSILE", newbRaw: 0 },
  { blueprintSet: "F", slot: 2, slotCategory: "station", designId: 0, shipSymbol: "SHIP_DODO", newbRaw: 64 },
  { blueprintSet: "F", slot: 3, slotCategory: "escape pod", designId: 2, shipSymbol: "SHIP_ESCAPE_POD", newbRaw: 65 },
  { blueprintSet: "F", slot: 4, slotCategory: "cargo", designId: 3, shipSymbol: "SHIP_PLATE", newbRaw: 0 },
  { blueprintSet: "F", slot: 5, slotCategory: "cargo", designId: 4, shipSymbol: "SHIP_CANISTER", newbRaw: 0 },
  { blueprintSet: "F", slot: 6, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "F", slot: 7, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "F", slot: 8, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "F", slot: 9, slotCategory: "shuttle", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "F", slot: 10, slotCategory: "transporter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "F", slot: 11, slotCategory: "trader", designId: 11, shipSymbol: "SHIP_PYTHON", newbRaw: 160 },
  { blueprintSet: "F", slot: 12, slotCategory: "trader", designId: 31, shipSymbol: "SHIP_OPHIDIAN", newbRaw: 161 },
  { blueprintSet: "F", slot: 13, slotCategory: "trader", designId: 12, shipSymbol: "SHIP_BOA", newbRaw: 160 },
  { blueprintSet: "F", slot: 14, slotCategory: "trader / large carrier", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "F", slot: 15, slotCategory: "small child ship", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "F", slot: 16, slotCategory: "cop", designId: 16, shipSymbol: "SHIP_VIPER", newbRaw: 194 },
  { blueprintSet: "F", slot: 17, slotCategory: "pirate", designId: 18, shipSymbol: "SHIP_MAMBA", newbRaw: 140 },
  { blueprintSet: "F", slot: 18, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "F", slot: 19, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "F", slot: 20, slotCategory: "pirate", designId: 33, shipSymbol: "SHIP_BUSHMASTER", newbRaw: 140 },
  { blueprintSet: "F", slot: 21, slotCategory: "pirate", designId: 31, shipSymbol: "SHIP_OPHIDIAN", newbRaw: 132 },
  { blueprintSet: "F", slot: 22, slotCategory: "pirate", designId: 11, shipSymbol: "SHIP_PYTHON", newbRaw: 140 },
  { blueprintSet: "F", slot: 23, slotCategory: "pirate", designId: 35, shipSymbol: "SHIP_IGUANA", newbRaw: 132 },
  { blueprintSet: "F", slot: 24, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "F", slot: 25, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "F", slot: 26, slotCategory: "bounty hunter", designId: 33, shipSymbol: "SHIP_BUSHMASTER", newbRaw: 162 },
  { blueprintSet: "F", slot: 27, slotCategory: "bounty hunter", designId: 11, shipSymbol: "SHIP_PYTHON", newbRaw: 130 },
  { blueprintSet: "F", slot: 28, slotCategory: "bounty hunter", designId: 31, shipSymbol: "SHIP_OPHIDIAN", newbRaw: 162 },
  { blueprintSet: "F", slot: 29, slotCategory: "Thargoid", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "F", slot: 30, slotCategory: "Thargon", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "F", slot: 31, slotCategory: "Constrictor", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "G", slot: 1, slotCategory: "missile", designId: 15, shipSymbol: "SHIP_MISSILE", newbRaw: 0 },
  { blueprintSet: "G", slot: 2, slotCategory: "station", designId: 1, shipSymbol: "SHIP_CORIOLIS", newbRaw: 64 },
  { blueprintSet: "G", slot: 3, slotCategory: "escape pod", designId: 2, shipSymbol: "SHIP_ESCAPE_POD", newbRaw: 65 },
  { blueprintSet: "G", slot: 4, slotCategory: "cargo", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "G", slot: 5, slotCategory: "cargo", designId: 4, shipSymbol: "SHIP_CANISTER", newbRaw: 0 },
  { blueprintSet: "G", slot: 6, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "G", slot: 7, slotCategory: "mining", designId: 6, shipSymbol: "SHIP_ASTEROID", newbRaw: 0 },
  { blueprintSet: "G", slot: 8, slotCategory: "mining", designId: 7, shipSymbol: "SHIP_SPLINTER", newbRaw: 0 },
  { blueprintSet: "G", slot: 9, slotCategory: "shuttle", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "G", slot: 10, slotCategory: "transporter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "G", slot: 11, slotCategory: "trader", designId: 12, shipSymbol: "SHIP_BOA", newbRaw: 160 },
  { blueprintSet: "G", slot: 12, slotCategory: "trader", designId: 20, shipSymbol: "SHIP_ADDER", newbRaw: 161 },
  { blueprintSet: "G", slot: 13, slotCategory: "trader", designId: 35, shipSymbol: "SHIP_IGUANA", newbRaw: 160 },
  { blueprintSet: "G", slot: 14, slotCategory: "trader / large carrier", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "G", slot: 15, slotCategory: "small child ship", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "G", slot: 16, slotCategory: "cop", designId: 16, shipSymbol: "SHIP_VIPER", newbRaw: 194 },
  { blueprintSet: "G", slot: 17, slotCategory: "pirate", designId: 21, shipSymbol: "SHIP_GECKO", newbRaw: 140 },
  { blueprintSet: "G", slot: 18, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "G", slot: 19, slotCategory: "pirate", designId: 20, shipSymbol: "SHIP_ADDER", newbRaw: 132 },
  { blueprintSet: "G", slot: 20, slotCategory: "pirate", designId: 35, shipSymbol: "SHIP_IGUANA", newbRaw: 140 },
  { blueprintSet: "G", slot: 21, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "G", slot: 22, slotCategory: "pirate", designId: 14, shipSymbol: "SHIP_WORM", newbRaw: 12 },
  { blueprintSet: "G", slot: 23, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "G", slot: 24, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "G", slot: 25, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "G", slot: 26, slotCategory: "bounty hunter", designId: 35, shipSymbol: "SHIP_IGUANA", newbRaw: 162 },
  { blueprintSet: "G", slot: 27, slotCategory: "bounty hunter", designId: 20, shipSymbol: "SHIP_ADDER", newbRaw: 130 },
  { blueprintSet: "G", slot: 28, slotCategory: "bounty hunter", designId: 21, shipSymbol: "SHIP_GECKO", newbRaw: 162 },
  { blueprintSet: "G", slot: 29, slotCategory: "Thargoid", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "G", slot: 30, slotCategory: "Thargon", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "G", slot: 31, slotCategory: "Constrictor", designId: 28, shipSymbol: "SHIP_CONSTRICTOR", newbRaw: 12 },
  { blueprintSet: "H", slot: 1, slotCategory: "missile", designId: 15, shipSymbol: "SHIP_MISSILE", newbRaw: 0 },
  { blueprintSet: "H", slot: 2, slotCategory: "station", designId: 0, shipSymbol: "SHIP_DODO", newbRaw: 64 },
  { blueprintSet: "H", slot: 3, slotCategory: "escape pod", designId: 2, shipSymbol: "SHIP_ESCAPE_POD", newbRaw: 65 },
  { blueprintSet: "H", slot: 4, slotCategory: "cargo", designId: 3, shipSymbol: "SHIP_PLATE", newbRaw: 0 },
  { blueprintSet: "H", slot: 5, slotCategory: "cargo", designId: 4, shipSymbol: "SHIP_CANISTER", newbRaw: 0 },
  { blueprintSet: "H", slot: 6, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "H", slot: 7, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "H", slot: 8, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "H", slot: 9, slotCategory: "shuttle", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "H", slot: 10, slotCategory: "transporter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "H", slot: 11, slotCategory: "trader", designId: 32, shipSymbol: "SHIP_GHAVIAL", newbRaw: 160 },
  { blueprintSet: "H", slot: 12, slotCategory: "trader", designId: 34, shipSymbol: "SHIP_RATTLER", newbRaw: 161 },
  { blueprintSet: "H", slot: 13, slotCategory: "trader", designId: 22, shipSymbol: "SHIP_COBRA_MK_1", newbRaw: 160 },
  { blueprintSet: "H", slot: 14, slotCategory: "trader / large carrier", designId: 13, shipSymbol: "SHIP_ANACONDA", newbRaw: 161 },
  { blueprintSet: "H", slot: 15, slotCategory: "small child ship", designId: 14, shipSymbol: "SHIP_WORM", newbRaw: 12 },
  { blueprintSet: "H", slot: 16, slotCategory: "cop", designId: 16, shipSymbol: "SHIP_VIPER", newbRaw: 194 },
  { blueprintSet: "H", slot: 17, slotCategory: "pirate", designId: 22, shipSymbol: "SHIP_COBRA_MK_1", newbRaw: 140 },
  { blueprintSet: "H", slot: 18, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "H", slot: 19, slotCategory: "pirate", designId: 20, shipSymbol: "SHIP_ADDER", newbRaw: 132 },
  { blueprintSet: "H", slot: 20, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "H", slot: 21, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "H", slot: 22, slotCategory: "pirate", designId: 14, shipSymbol: "SHIP_WORM", newbRaw: 12 },
  { blueprintSet: "H", slot: 23, slotCategory: "pirate", designId: 34, shipSymbol: "SHIP_RATTLER", newbRaw: 132 },
  { blueprintSet: "H", slot: 24, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "H", slot: 25, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "H", slot: 26, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "H", slot: 27, slotCategory: "bounty hunter", designId: 22, shipSymbol: "SHIP_COBRA_MK_1", newbRaw: 130 },
  { blueprintSet: "H", slot: 28, slotCategory: "bounty hunter", designId: 34, shipSymbol: "SHIP_RATTLER", newbRaw: 162 },
  { blueprintSet: "H", slot: 29, slotCategory: "Thargoid", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "H", slot: 30, slotCategory: "Thargon", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "H", slot: 31, slotCategory: "Constrictor", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "I", slot: 1, slotCategory: "missile", designId: 15, shipSymbol: "SHIP_MISSILE", newbRaw: 0 },
  { blueprintSet: "I", slot: 2, slotCategory: "station", designId: 1, shipSymbol: "SHIP_CORIOLIS", newbRaw: 64 },
  { blueprintSet: "I", slot: 3, slotCategory: "escape pod", designId: 2, shipSymbol: "SHIP_ESCAPE_POD", newbRaw: 65 },
  { blueprintSet: "I", slot: 4, slotCategory: "cargo", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "I", slot: 5, slotCategory: "cargo", designId: 4, shipSymbol: "SHIP_CANISTER", newbRaw: 0 },
  { blueprintSet: "I", slot: 6, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "I", slot: 7, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "I", slot: 8, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "I", slot: 9, slotCategory: "shuttle", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "I", slot: 10, slotCategory: "transporter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "I", slot: 11, slotCategory: "trader", designId: 32, shipSymbol: "SHIP_GHAVIAL", newbRaw: 160 },
  { blueprintSet: "I", slot: 12, slotCategory: "trader", designId: 31, shipSymbol: "SHIP_OPHIDIAN", newbRaw: 161 },
  { blueprintSet: "I", slot: 13, slotCategory: "trader", designId: 22, shipSymbol: "SHIP_COBRA_MK_1", newbRaw: 160 },
  { blueprintSet: "I", slot: 14, slotCategory: "trader / large carrier", designId: 13, shipSymbol: "SHIP_ANACONDA", newbRaw: 161 },
  { blueprintSet: "I", slot: 15, slotCategory: "small child ship", designId: 14, shipSymbol: "SHIP_WORM", newbRaw: 12 },
  { blueprintSet: "I", slot: 16, slotCategory: "cop", designId: 16, shipSymbol: "SHIP_VIPER", newbRaw: 194 },
  { blueprintSet: "I", slot: 17, slotCategory: "pirate", designId: 19, shipSymbol: "SHIP_KRAIT", newbRaw: 140 },
  { blueprintSet: "I", slot: 18, slotCategory: "pirate", designId: 22, shipSymbol: "SHIP_COBRA_MK_1", newbRaw: 140 },
  { blueprintSet: "I", slot: 19, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "I", slot: 20, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "I", slot: 21, slotCategory: "pirate", designId: 31, shipSymbol: "SHIP_OPHIDIAN", newbRaw: 132 },
  { blueprintSet: "I", slot: 22, slotCategory: "pirate", designId: 14, shipSymbol: "SHIP_WORM", newbRaw: 12 },
  { blueprintSet: "I", slot: 23, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "I", slot: 24, slotCategory: "pirate", designId: 23, shipSymbol: "SHIP_ASP_MK_2", newbRaw: 140 },
  { blueprintSet: "I", slot: 25, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "I", slot: 26, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "I", slot: 27, slotCategory: "bounty hunter", designId: 23, shipSymbol: "SHIP_ASP_MK_2", newbRaw: 130 },
  { blueprintSet: "I", slot: 28, slotCategory: "bounty hunter", designId: 19, shipSymbol: "SHIP_KRAIT", newbRaw: 162 },
  { blueprintSet: "I", slot: 29, slotCategory: "Thargoid", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "I", slot: 30, slotCategory: "Thargon", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "I", slot: 31, slotCategory: "Constrictor", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "J", slot: 1, slotCategory: "missile", designId: 15, shipSymbol: "SHIP_MISSILE", newbRaw: 0 },
  { blueprintSet: "J", slot: 2, slotCategory: "station", designId: 0, shipSymbol: "SHIP_DODO", newbRaw: 64 },
  { blueprintSet: "J", slot: 3, slotCategory: "escape pod", designId: 2, shipSymbol: "SHIP_ESCAPE_POD", newbRaw: 65 },
  { blueprintSet: "J", slot: 4, slotCategory: "cargo", designId: 3, shipSymbol: "SHIP_PLATE", newbRaw: 0 },
  { blueprintSet: "J", slot: 5, slotCategory: "cargo", designId: 4, shipSymbol: "SHIP_CANISTER", newbRaw: 0 },
  { blueprintSet: "J", slot: 6, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "J", slot: 7, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "J", slot: 8, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "J", slot: 9, slotCategory: "shuttle", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "J", slot: 10, slotCategory: "transporter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "J", slot: 11, slotCategory: "trader", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "J", slot: 12, slotCategory: "trader", designId: 25, shipSymbol: "SHIP_MORAY", newbRaw: 161 },
  { blueprintSet: "J", slot: 13, slotCategory: "trader", designId: 24, shipSymbol: "SHIP_FER_DE_LANCE", newbRaw: 160 },
  { blueprintSet: "J", slot: 14, slotCategory: "trader / large carrier", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "J", slot: 15, slotCategory: "small child ship", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "J", slot: 16, slotCategory: "cop", designId: 16, shipSymbol: "SHIP_VIPER", newbRaw: 194 },
  { blueprintSet: "J", slot: 17, slotCategory: "pirate", designId: 18, shipSymbol: "SHIP_MAMBA", newbRaw: 140 },
  { blueprintSet: "J", slot: 18, slotCategory: "pirate", designId: 17, shipSymbol: "SHIP_SIDEWINDER", newbRaw: 12 },
  { blueprintSet: "J", slot: 19, slotCategory: "pirate", designId: 21, shipSymbol: "SHIP_GECKO", newbRaw: 132 },
  { blueprintSet: "J", slot: 20, slotCategory: "pirate", designId: 33, shipSymbol: "SHIP_BUSHMASTER", newbRaw: 140 },
  { blueprintSet: "J", slot: 21, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "J", slot: 22, slotCategory: "pirate", designId: 25, shipSymbol: "SHIP_MORAY", newbRaw: 140 },
  { blueprintSet: "J", slot: 23, slotCategory: "pirate", designId: 14, shipSymbol: "SHIP_WORM", newbRaw: 4 },
  { blueprintSet: "J", slot: 24, slotCategory: "pirate", designId: 24, shipSymbol: "SHIP_FER_DE_LANCE", newbRaw: 140 },
  { blueprintSet: "J", slot: 25, slotCategory: "bounty hunter", designId: 24, shipSymbol: "SHIP_FER_DE_LANCE", newbRaw: 130 },
  { blueprintSet: "J", slot: 26, slotCategory: "bounty hunter", designId: 33, shipSymbol: "SHIP_BUSHMASTER", newbRaw: 162 },
  { blueprintSet: "J", slot: 27, slotCategory: "bounty hunter", designId: 25, shipSymbol: "SHIP_MORAY", newbRaw: 130 },
  { blueprintSet: "J", slot: 28, slotCategory: "bounty hunter", designId: 18, shipSymbol: "SHIP_MAMBA", newbRaw: 162 },
  { blueprintSet: "J", slot: 29, slotCategory: "Thargoid", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "J", slot: 30, slotCategory: "Thargon", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "J", slot: 31, slotCategory: "Constrictor", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "K", slot: 1, slotCategory: "missile", designId: 15, shipSymbol: "SHIP_MISSILE", newbRaw: 0 },
  { blueprintSet: "K", slot: 2, slotCategory: "station", designId: 1, shipSymbol: "SHIP_CORIOLIS", newbRaw: 64 },
  { blueprintSet: "K", slot: 3, slotCategory: "escape pod", designId: 2, shipSymbol: "SHIP_ESCAPE_POD", newbRaw: 65 },
  { blueprintSet: "K", slot: 4, slotCategory: "cargo", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "K", slot: 5, slotCategory: "cargo", designId: 4, shipSymbol: "SHIP_CANISTER", newbRaw: 0 },
  { blueprintSet: "K", slot: 6, slotCategory: "mining", designId: 5, shipSymbol: "SHIP_BOULDER", newbRaw: 0 },
  { blueprintSet: "K", slot: 7, slotCategory: "mining", designId: 6, shipSymbol: "SHIP_ASTEROID", newbRaw: 0 },
  { blueprintSet: "K", slot: 8, slotCategory: "mining", designId: 7, shipSymbol: "SHIP_SPLINTER", newbRaw: 0 },
  { blueprintSet: "K", slot: 9, slotCategory: "shuttle", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "K", slot: 10, slotCategory: "transporter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "K", slot: 11, slotCategory: "trader", designId: 12, shipSymbol: "SHIP_BOA", newbRaw: 160 },
  { blueprintSet: "K", slot: 12, slotCategory: "trader", designId: 31, shipSymbol: "SHIP_OPHIDIAN", newbRaw: 161 },
  { blueprintSet: "K", slot: 13, slotCategory: "trader", designId: 24, shipSymbol: "SHIP_FER_DE_LANCE", newbRaw: 160 },
  { blueprintSet: "K", slot: 14, slotCategory: "trader / large carrier", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "K", slot: 15, slotCategory: "small child ship", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "K", slot: 16, slotCategory: "cop", designId: 16, shipSymbol: "SHIP_VIPER", newbRaw: 194 },
  { blueprintSet: "K", slot: 17, slotCategory: "pirate", designId: 21, shipSymbol: "SHIP_GECKO", newbRaw: 140 },
  { blueprintSet: "K", slot: 18, slotCategory: "pirate", designId: 19, shipSymbol: "SHIP_KRAIT", newbRaw: 140 },
  { blueprintSet: "K", slot: 19, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "K", slot: 20, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "K", slot: 21, slotCategory: "pirate", designId: 31, shipSymbol: "SHIP_OPHIDIAN", newbRaw: 132 },
  { blueprintSet: "K", slot: 22, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "K", slot: 23, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "K", slot: 24, slotCategory: "pirate", designId: 24, shipSymbol: "SHIP_FER_DE_LANCE", newbRaw: 140 },
  { blueprintSet: "K", slot: 25, slotCategory: "bounty hunter", designId: 24, shipSymbol: "SHIP_FER_DE_LANCE", newbRaw: 130 },
  { blueprintSet: "K", slot: 26, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "K", slot: 27, slotCategory: "bounty hunter", designId: 21, shipSymbol: "SHIP_GECKO", newbRaw: 130 },
  { blueprintSet: "K", slot: 28, slotCategory: "bounty hunter", designId: 31, shipSymbol: "SHIP_OPHIDIAN", newbRaw: 162 },
  { blueprintSet: "K", slot: 29, slotCategory: "Thargoid", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "K", slot: 30, slotCategory: "Thargon", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "K", slot: 31, slotCategory: "Constrictor", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "L", slot: 1, slotCategory: "missile", designId: 15, shipSymbol: "SHIP_MISSILE", newbRaw: 0 },
  { blueprintSet: "L", slot: 2, slotCategory: "station", designId: 0, shipSymbol: "SHIP_DODO", newbRaw: 64 },
  { blueprintSet: "L", slot: 3, slotCategory: "escape pod", designId: 2, shipSymbol: "SHIP_ESCAPE_POD", newbRaw: 65 },
  { blueprintSet: "L", slot: 4, slotCategory: "cargo", designId: 3, shipSymbol: "SHIP_PLATE", newbRaw: 0 },
  { blueprintSet: "L", slot: 5, slotCategory: "cargo", designId: 4, shipSymbol: "SHIP_CANISTER", newbRaw: 0 },
  { blueprintSet: "L", slot: 6, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "L", slot: 7, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "L", slot: 8, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "L", slot: 9, slotCategory: "shuttle", designId: 8, shipSymbol: "SHIP_SHUTTLE", newbRaw: 33 },
  { blueprintSet: "L", slot: 10, slotCategory: "transporter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "L", slot: 11, slotCategory: "trader", designId: 12, shipSymbol: "SHIP_BOA", newbRaw: 160 },
  { blueprintSet: "L", slot: 12, slotCategory: "trader", designId: 31, shipSymbol: "SHIP_OPHIDIAN", newbRaw: 161 },
  { blueprintSet: "L", slot: 13, slotCategory: "trader", designId: 37, shipSymbol: "SHIP_CHAMELEON", newbRaw: 160 },
  { blueprintSet: "L", slot: 14, slotCategory: "trader / large carrier", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "L", slot: 15, slotCategory: "small child ship", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "L", slot: 16, slotCategory: "cop", designId: 16, shipSymbol: "SHIP_VIPER", newbRaw: 194 },
  { blueprintSet: "L", slot: 17, slotCategory: "pirate", designId: 17, shipSymbol: "SHIP_SIDEWINDER", newbRaw: 12 },
  { blueprintSet: "L", slot: 18, slotCategory: "pirate", designId: 19, shipSymbol: "SHIP_KRAIT", newbRaw: 140 },
  { blueprintSet: "L", slot: 19, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "L", slot: 20, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "L", slot: 21, slotCategory: "pirate", designId: 31, shipSymbol: "SHIP_OPHIDIAN", newbRaw: 132 },
  { blueprintSet: "L", slot: 22, slotCategory: "pirate", designId: 37, shipSymbol: "SHIP_CHAMELEON", newbRaw: 140 },
  { blueprintSet: "L", slot: 23, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "L", slot: 24, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "L", slot: 25, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "L", slot: 26, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "L", slot: 27, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "L", slot: 28, slotCategory: "bounty hunter", designId: 17, shipSymbol: "SHIP_SIDEWINDER", newbRaw: 34 },
  { blueprintSet: "L", slot: 29, slotCategory: "Thargoid", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "L", slot: 30, slotCategory: "Thargon", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "L", slot: 31, slotCategory: "Constrictor", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "M", slot: 1, slotCategory: "missile", designId: 15, shipSymbol: "SHIP_MISSILE", newbRaw: 0 },
  { blueprintSet: "M", slot: 2, slotCategory: "station", designId: 1, shipSymbol: "SHIP_CORIOLIS", newbRaw: 64 },
  { blueprintSet: "M", slot: 3, slotCategory: "escape pod", designId: 2, shipSymbol: "SHIP_ESCAPE_POD", newbRaw: 65 },
  { blueprintSet: "M", slot: 4, slotCategory: "cargo", designId: 3, shipSymbol: "SHIP_PLATE", newbRaw: 0 },
  { blueprintSet: "M", slot: 5, slotCategory: "cargo", designId: 4, shipSymbol: "SHIP_CANISTER", newbRaw: 0 },
  { blueprintSet: "M", slot: 6, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "M", slot: 7, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "M", slot: 8, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "M", slot: 9, slotCategory: "shuttle", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "M", slot: 10, slotCategory: "transporter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "M", slot: 11, slotCategory: "trader", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "M", slot: 12, slotCategory: "trader", designId: 31, shipSymbol: "SHIP_OPHIDIAN", newbRaw: 161 },
  { blueprintSet: "M", slot: 13, slotCategory: "trader", designId: 24, shipSymbol: "SHIP_FER_DE_LANCE", newbRaw: 160 },
  { blueprintSet: "M", slot: 14, slotCategory: "trader / large carrier", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "M", slot: 15, slotCategory: "small child ship", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "M", slot: 16, slotCategory: "cop", designId: 16, shipSymbol: "SHIP_VIPER", newbRaw: 194 },
  { blueprintSet: "M", slot: 17, slotCategory: "pirate", designId: 18, shipSymbol: "SHIP_MAMBA", newbRaw: 140 },
  { blueprintSet: "M", slot: 18, slotCategory: "pirate", designId: 22, shipSymbol: "SHIP_COBRA_MK_1", newbRaw: 140 },
  { blueprintSet: "M", slot: 19, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "M", slot: 20, slotCategory: "pirate", designId: 33, shipSymbol: "SHIP_BUSHMASTER", newbRaw: 140 },
  { blueprintSet: "M", slot: 21, slotCategory: "pirate", designId: 31, shipSymbol: "SHIP_OPHIDIAN", newbRaw: 132 },
  { blueprintSet: "M", slot: 22, slotCategory: "pirate", designId: 37, shipSymbol: "SHIP_CHAMELEON", newbRaw: 140 },
  { blueprintSet: "M", slot: 23, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "M", slot: 24, slotCategory: "pirate", designId: 24, shipSymbol: "SHIP_FER_DE_LANCE", newbRaw: 140 },
  { blueprintSet: "M", slot: 25, slotCategory: "bounty hunter", designId: 24, shipSymbol: "SHIP_FER_DE_LANCE", newbRaw: 130 },
  { blueprintSet: "M", slot: 26, slotCategory: "bounty hunter", designId: 33, shipSymbol: "SHIP_BUSHMASTER", newbRaw: 162 },
  { blueprintSet: "M", slot: 27, slotCategory: "bounty hunter", designId: 22, shipSymbol: "SHIP_COBRA_MK_1", newbRaw: 130 },
  { blueprintSet: "M", slot: 28, slotCategory: "bounty hunter", designId: 18, shipSymbol: "SHIP_MAMBA", newbRaw: 162 },
  { blueprintSet: "M", slot: 29, slotCategory: "Thargoid", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "M", slot: 30, slotCategory: "Thargon", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "M", slot: 31, slotCategory: "Constrictor", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "N", slot: 1, slotCategory: "missile", designId: 15, shipSymbol: "SHIP_MISSILE", newbRaw: 0 },
  { blueprintSet: "N", slot: 2, slotCategory: "station", designId: 0, shipSymbol: "SHIP_DODO", newbRaw: 64 },
  { blueprintSet: "N", slot: 3, slotCategory: "escape pod", designId: 2, shipSymbol: "SHIP_ESCAPE_POD", newbRaw: 65 },
  { blueprintSet: "N", slot: 4, slotCategory: "cargo", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "N", slot: 5, slotCategory: "cargo", designId: 4, shipSymbol: "SHIP_CANISTER", newbRaw: 0 },
  { blueprintSet: "N", slot: 6, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "N", slot: 7, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "N", slot: 8, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "N", slot: 9, slotCategory: "shuttle", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "N", slot: 10, slotCategory: "transporter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "N", slot: 11, slotCategory: "trader", designId: 10, shipSymbol: "SHIP_COBRA_MK_3", newbRaw: 160 },
  { blueprintSet: "N", slot: 12, slotCategory: "trader", designId: 34, shipSymbol: "SHIP_RATTLER", newbRaw: 161 },
  { blueprintSet: "N", slot: 13, slotCategory: "trader", designId: 11, shipSymbol: "SHIP_PYTHON", newbRaw: 160 },
  { blueprintSet: "N", slot: 14, slotCategory: "trader / large carrier", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "N", slot: 15, slotCategory: "small child ship", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "N", slot: 16, slotCategory: "cop", designId: 16, shipSymbol: "SHIP_VIPER", newbRaw: 194 },
  { blueprintSet: "N", slot: 17, slotCategory: "pirate", designId: 21, shipSymbol: "SHIP_GECKO", newbRaw: 140 },
  { blueprintSet: "N", slot: 18, slotCategory: "pirate", designId: 19, shipSymbol: "SHIP_KRAIT", newbRaw: 140 },
  { blueprintSet: "N", slot: 19, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "N", slot: 20, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "N", slot: 21, slotCategory: "pirate", designId: 10, shipSymbol: "SHIP_COBRA_MK_3", newbRaw: 132 },
  { blueprintSet: "N", slot: 22, slotCategory: "pirate", designId: 34, shipSymbol: "SHIP_RATTLER", newbRaw: 140 },
  { blueprintSet: "N", slot: 23, slotCategory: "pirate", designId: 11, shipSymbol: "SHIP_PYTHON", newbRaw: 132 },
  { blueprintSet: "N", slot: 24, slotCategory: "pirate", designId: 23, shipSymbol: "SHIP_ASP_MK_2", newbRaw: 140 },
  { blueprintSet: "N", slot: 25, slotCategory: "bounty hunter", designId: 10, shipSymbol: "SHIP_COBRA_MK_3", newbRaw: 130 },
  { blueprintSet: "N", slot: 26, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "N", slot: 27, slotCategory: "bounty hunter", designId: 21, shipSymbol: "SHIP_GECKO", newbRaw: 130 },
  { blueprintSet: "N", slot: 28, slotCategory: "bounty hunter", designId: 34, shipSymbol: "SHIP_RATTLER", newbRaw: 162 },
  { blueprintSet: "N", slot: 29, slotCategory: "Thargoid", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "N", slot: 30, slotCategory: "Thargon", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "N", slot: 31, slotCategory: "Constrictor", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "O", slot: 1, slotCategory: "missile", designId: 15, shipSymbol: "SHIP_MISSILE", newbRaw: 0 },
  { blueprintSet: "O", slot: 2, slotCategory: "station", designId: 1, shipSymbol: "SHIP_CORIOLIS", newbRaw: 64 },
  { blueprintSet: "O", slot: 3, slotCategory: "escape pod", designId: 2, shipSymbol: "SHIP_ESCAPE_POD", newbRaw: 65 },
  { blueprintSet: "O", slot: 4, slotCategory: "cargo", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "O", slot: 5, slotCategory: "cargo", designId: 4, shipSymbol: "SHIP_CANISTER", newbRaw: 0 },
  { blueprintSet: "O", slot: 6, slotCategory: "mining", designId: 5, shipSymbol: "SHIP_BOULDER", newbRaw: 0 },
  { blueprintSet: "O", slot: 7, slotCategory: "mining", designId: 6, shipSymbol: "SHIP_ASTEROID", newbRaw: 0 },
  { blueprintSet: "O", slot: 8, slotCategory: "mining", designId: 7, shipSymbol: "SHIP_SPLINTER", newbRaw: 0 },
  { blueprintSet: "O", slot: 9, slotCategory: "shuttle", designId: 36, shipSymbol: "SHIP_SHUTTLE_MK_2", newbRaw: 33 },
  { blueprintSet: "O", slot: 10, slotCategory: "transporter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "O", slot: 11, slotCategory: "trader", designId: 11, shipSymbol: "SHIP_PYTHON", newbRaw: 160 },
  { blueprintSet: "O", slot: 12, slotCategory: "trader", designId: 25, shipSymbol: "SHIP_MORAY", newbRaw: 161 },
  { blueprintSet: "O", slot: 13, slotCategory: "trader", designId: 20, shipSymbol: "SHIP_ADDER", newbRaw: 160 },
  { blueprintSet: "O", slot: 14, slotCategory: "trader / large carrier", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "O", slot: 15, slotCategory: "small child ship", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "O", slot: 16, slotCategory: "cop", designId: 16, shipSymbol: "SHIP_VIPER", newbRaw: 194 },
  { blueprintSet: "O", slot: 17, slotCategory: "pirate", designId: 22, shipSymbol: "SHIP_COBRA_MK_1", newbRaw: 140 },
  { blueprintSet: "O", slot: 18, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "O", slot: 19, slotCategory: "pirate", designId: 20, shipSymbol: "SHIP_ADDER", newbRaw: 132 },
  { blueprintSet: "O", slot: 20, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "O", slot: 21, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "O", slot: 22, slotCategory: "pirate", designId: 25, shipSymbol: "SHIP_MORAY", newbRaw: 140 },
  { blueprintSet: "O", slot: 23, slotCategory: "pirate", designId: 11, shipSymbol: "SHIP_PYTHON", newbRaw: 132 },
  { blueprintSet: "O", slot: 24, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "O", slot: 25, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "O", slot: 26, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "O", slot: 27, slotCategory: "bounty hunter", designId: 25, shipSymbol: "SHIP_MORAY", newbRaw: 130 },
  { blueprintSet: "O", slot: 28, slotCategory: "bounty hunter", designId: 20, shipSymbol: "SHIP_ADDER", newbRaw: 162 },
  { blueprintSet: "O", slot: 29, slotCategory: "Thargoid", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "O", slot: 30, slotCategory: "Thargon", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "O", slot: 31, slotCategory: "Constrictor", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "P", slot: 1, slotCategory: "missile", designId: 15, shipSymbol: "SHIP_MISSILE", newbRaw: 0 },
  { blueprintSet: "P", slot: 2, slotCategory: "station", designId: 0, shipSymbol: "SHIP_DODO", newbRaw: 64 },
  { blueprintSet: "P", slot: 3, slotCategory: "escape pod", designId: 2, shipSymbol: "SHIP_ESCAPE_POD", newbRaw: 65 },
  { blueprintSet: "P", slot: 4, slotCategory: "cargo", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "P", slot: 5, slotCategory: "cargo", designId: 4, shipSymbol: "SHIP_CANISTER", newbRaw: 0 },
  { blueprintSet: "P", slot: 6, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "P", slot: 7, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "P", slot: 8, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "P", slot: 9, slotCategory: "shuttle", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "P", slot: 10, slotCategory: "transporter", designId: 9, shipSymbol: "SHIP_TRANSPORTER", newbRaw: 97 },
  { blueprintSet: "P", slot: 11, slotCategory: "trader", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "P", slot: 12, slotCategory: "trader", designId: 37, shipSymbol: "SHIP_CHAMELEON", newbRaw: 161 },
  { blueprintSet: "P", slot: 13, slotCategory: "trader", designId: 31, shipSymbol: "SHIP_OPHIDIAN", newbRaw: 160 },
  { blueprintSet: "P", slot: 14, slotCategory: "trader / large carrier", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "P", slot: 15, slotCategory: "small child ship", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "P", slot: 16, slotCategory: "cop", designId: 16, shipSymbol: "SHIP_VIPER", newbRaw: 194 },
  { blueprintSet: "P", slot: 17, slotCategory: "pirate", designId: 18, shipSymbol: "SHIP_MAMBA", newbRaw: 140 },
  { blueprintSet: "P", slot: 18, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "P", slot: 19, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "P", slot: 20, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "P", slot: 21, slotCategory: "pirate", designId: 31, shipSymbol: "SHIP_OPHIDIAN", newbRaw: 132 },
  { blueprintSet: "P", slot: 22, slotCategory: "pirate", designId: 37, shipSymbol: "SHIP_CHAMELEON", newbRaw: 140 },
  { blueprintSet: "P", slot: 23, slotCategory: "pirate", designId: 25, shipSymbol: "SHIP_MORAY", newbRaw: 132 },
  { blueprintSet: "P", slot: 24, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "P", slot: 25, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "P", slot: 26, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "P", slot: 27, slotCategory: "bounty hunter", designId: 25, shipSymbol: "SHIP_MORAY", newbRaw: 130 },
  { blueprintSet: "P", slot: 28, slotCategory: "bounty hunter", designId: 37, shipSymbol: "SHIP_CHAMELEON", newbRaw: 162 },
  { blueprintSet: "P", slot: 29, slotCategory: "Thargoid", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "P", slot: 30, slotCategory: "Thargon", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "P", slot: 31, slotCategory: "Constrictor", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "Q", slot: 1, slotCategory: "missile", designId: 15, shipSymbol: "SHIP_MISSILE", newbRaw: 0 },
  { blueprintSet: "Q", slot: 2, slotCategory: "station", designId: 1, shipSymbol: "SHIP_CORIOLIS", newbRaw: 64 },
  { blueprintSet: "Q", slot: 3, slotCategory: "escape pod", designId: 2, shipSymbol: "SHIP_ESCAPE_POD", newbRaw: 65 },
  { blueprintSet: "Q", slot: 4, slotCategory: "cargo", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "Q", slot: 5, slotCategory: "cargo", designId: 4, shipSymbol: "SHIP_CANISTER", newbRaw: 0 },
  { blueprintSet: "Q", slot: 6, slotCategory: "mining", designId: 5, shipSymbol: "SHIP_BOULDER", newbRaw: 0 },
  { blueprintSet: "Q", slot: 7, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "Q", slot: 8, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "Q", slot: 9, slotCategory: "shuttle", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "Q", slot: 10, slotCategory: "transporter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "Q", slot: 11, slotCategory: "trader", designId: 10, shipSymbol: "SHIP_COBRA_MK_3", newbRaw: 160 },
  { blueprintSet: "Q", slot: 12, slotCategory: "trader", designId: 11, shipSymbol: "SHIP_PYTHON", newbRaw: 161 },
  { blueprintSet: "Q", slot: 13, slotCategory: "trader", designId: 35, shipSymbol: "SHIP_IGUANA", newbRaw: 160 },
  { blueprintSet: "Q", slot: 14, slotCategory: "trader / large carrier", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "Q", slot: 15, slotCategory: "small child ship", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "Q", slot: 16, slotCategory: "cop", designId: 16, shipSymbol: "SHIP_VIPER", newbRaw: 194 },
  { blueprintSet: "Q", slot: 17, slotCategory: "pirate", designId: 21, shipSymbol: "SHIP_GECKO", newbRaw: 140 },
  { blueprintSet: "Q", slot: 18, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "Q", slot: 19, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "Q", slot: 20, slotCategory: "pirate", designId: 33, shipSymbol: "SHIP_BUSHMASTER", newbRaw: 140 },
  { blueprintSet: "Q", slot: 21, slotCategory: "pirate", designId: 10, shipSymbol: "SHIP_COBRA_MK_3", newbRaw: 132 },
  { blueprintSet: "Q", slot: 22, slotCategory: "pirate", designId: 11, shipSymbol: "SHIP_PYTHON", newbRaw: 140 },
  { blueprintSet: "Q", slot: 23, slotCategory: "pirate", designId: 35, shipSymbol: "SHIP_IGUANA", newbRaw: 132 },
  { blueprintSet: "Q", slot: 24, slotCategory: "pirate", designId: 25, shipSymbol: "SHIP_MORAY", newbRaw: 140 },
  { blueprintSet: "Q", slot: 25, slotCategory: "bounty hunter", designId: 10, shipSymbol: "SHIP_COBRA_MK_3", newbRaw: 130 },
  { blueprintSet: "Q", slot: 26, slotCategory: "bounty hunter", designId: 33, shipSymbol: "SHIP_BUSHMASTER", newbRaw: 162 },
  { blueprintSet: "Q", slot: 27, slotCategory: "bounty hunter", designId: 21, shipSymbol: "SHIP_GECKO", newbRaw: 130 },
  { blueprintSet: "Q", slot: 28, slotCategory: "bounty hunter", designId: 11, shipSymbol: "SHIP_PYTHON", newbRaw: 162 },
  { blueprintSet: "Q", slot: 29, slotCategory: "Thargoid", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "Q", slot: 30, slotCategory: "Thargon", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "Q", slot: 31, slotCategory: "Constrictor", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "R", slot: 1, slotCategory: "missile", designId: 15, shipSymbol: "SHIP_MISSILE", newbRaw: 0 },
  { blueprintSet: "R", slot: 2, slotCategory: "station", designId: 0, shipSymbol: "SHIP_DODO", newbRaw: 64 },
  { blueprintSet: "R", slot: 3, slotCategory: "escape pod", designId: 2, shipSymbol: "SHIP_ESCAPE_POD", newbRaw: 65 },
  { blueprintSet: "R", slot: 4, slotCategory: "cargo", designId: 3, shipSymbol: "SHIP_PLATE", newbRaw: 0 },
  { blueprintSet: "R", slot: 5, slotCategory: "cargo", designId: 4, shipSymbol: "SHIP_CANISTER", newbRaw: 0 },
  { blueprintSet: "R", slot: 6, slotCategory: "mining", designId: 5, shipSymbol: "SHIP_BOULDER", newbRaw: 0 },
  { blueprintSet: "R", slot: 7, slotCategory: "mining", designId: 6, shipSymbol: "SHIP_ASTEROID", newbRaw: 0 },
  { blueprintSet: "R", slot: 8, slotCategory: "mining", designId: 7, shipSymbol: "SHIP_SPLINTER", newbRaw: 0 },
  { blueprintSet: "R", slot: 9, slotCategory: "shuttle", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "R", slot: 10, slotCategory: "transporter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "R", slot: 11, slotCategory: "trader", designId: 12, shipSymbol: "SHIP_BOA", newbRaw: 160 },
  { blueprintSet: "R", slot: 12, slotCategory: "trader", designId: 31, shipSymbol: "SHIP_OPHIDIAN", newbRaw: 161 },
  { blueprintSet: "R", slot: 13, slotCategory: "trader", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "R", slot: 14, slotCategory: "trader / large carrier", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "R", slot: 15, slotCategory: "small child ship", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "R", slot: 16, slotCategory: "cop", designId: 16, shipSymbol: "SHIP_VIPER", newbRaw: 194 },
  { blueprintSet: "R", slot: 17, slotCategory: "pirate", designId: 17, shipSymbol: "SHIP_SIDEWINDER", newbRaw: 12 },
  { blueprintSet: "R", slot: 18, slotCategory: "pirate", designId: 21, shipSymbol: "SHIP_GECKO", newbRaw: 140 },
  { blueprintSet: "R", slot: 19, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "R", slot: 20, slotCategory: "pirate", designId: 33, shipSymbol: "SHIP_BUSHMASTER", newbRaw: 140 },
  { blueprintSet: "R", slot: 21, slotCategory: "pirate", designId: 31, shipSymbol: "SHIP_OPHIDIAN", newbRaw: 132 },
  { blueprintSet: "R", slot: 22, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "R", slot: 23, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "R", slot: 24, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "R", slot: 25, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "R", slot: 26, slotCategory: "bounty hunter", designId: 33, shipSymbol: "SHIP_BUSHMASTER", newbRaw: 162 },
  { blueprintSet: "R", slot: 27, slotCategory: "bounty hunter", designId: 21, shipSymbol: "SHIP_GECKO", newbRaw: 130 },
  { blueprintSet: "R", slot: 28, slotCategory: "bounty hunter", designId: 17, shipSymbol: "SHIP_SIDEWINDER", newbRaw: 34 },
  { blueprintSet: "R", slot: 29, slotCategory: "Thargoid", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "R", slot: 30, slotCategory: "Thargon", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "R", slot: 31, slotCategory: "Constrictor", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "S", slot: 1, slotCategory: "missile", designId: 15, shipSymbol: "SHIP_MISSILE", newbRaw: 0 },
  { blueprintSet: "S", slot: 2, slotCategory: "station", designId: 1, shipSymbol: "SHIP_CORIOLIS", newbRaw: 64 },
  { blueprintSet: "S", slot: 3, slotCategory: "escape pod", designId: 2, shipSymbol: "SHIP_ESCAPE_POD", newbRaw: 65 },
  { blueprintSet: "S", slot: 4, slotCategory: "cargo", designId: 3, shipSymbol: "SHIP_PLATE", newbRaw: 0 },
  { blueprintSet: "S", slot: 5, slotCategory: "cargo", designId: 4, shipSymbol: "SHIP_CANISTER", newbRaw: 0 },
  { blueprintSet: "S", slot: 6, slotCategory: "mining", designId: 5, shipSymbol: "SHIP_BOULDER", newbRaw: 0 },
  { blueprintSet: "S", slot: 7, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "S", slot: 8, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "S", slot: 9, slotCategory: "shuttle", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "S", slot: 10, slotCategory: "transporter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "S", slot: 11, slotCategory: "trader", designId: 32, shipSymbol: "SHIP_GHAVIAL", newbRaw: 160 },
  { blueprintSet: "S", slot: 12, slotCategory: "trader", designId: 30, shipSymbol: "SHIP_MONITOR", newbRaw: 161 },
  { blueprintSet: "S", slot: 13, slotCategory: "trader", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "S", slot: 14, slotCategory: "trader / large carrier", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "S", slot: 15, slotCategory: "small child ship", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "S", slot: 16, slotCategory: "cop", designId: 16, shipSymbol: "SHIP_VIPER", newbRaw: 194 },
  { blueprintSet: "S", slot: 17, slotCategory: "pirate", designId: 17, shipSymbol: "SHIP_SIDEWINDER", newbRaw: 12 },
  { blueprintSet: "S", slot: 18, slotCategory: "pirate", designId: 21, shipSymbol: "SHIP_GECKO", newbRaw: 140 },
  { blueprintSet: "S", slot: 19, slotCategory: "pirate", designId: 18, shipSymbol: "SHIP_MAMBA", newbRaw: 132 },
  { blueprintSet: "S", slot: 20, slotCategory: "pirate", designId: 33, shipSymbol: "SHIP_BUSHMASTER", newbRaw: 140 },
  { blueprintSet: "S", slot: 21, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "S", slot: 22, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "S", slot: 23, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "S", slot: 24, slotCategory: "pirate", designId: 30, shipSymbol: "SHIP_MONITOR", newbRaw: 140 },
  { blueprintSet: "S", slot: 25, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "S", slot: 26, slotCategory: "bounty hunter", designId: 33, shipSymbol: "SHIP_BUSHMASTER", newbRaw: 162 },
  { blueprintSet: "S", slot: 27, slotCategory: "bounty hunter", designId: 21, shipSymbol: "SHIP_GECKO", newbRaw: 130 },
  { blueprintSet: "S", slot: 28, slotCategory: "bounty hunter", designId: 17, shipSymbol: "SHIP_SIDEWINDER", newbRaw: 34 },
  { blueprintSet: "S", slot: 29, slotCategory: "Thargoid", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "S", slot: 30, slotCategory: "Thargon", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "S", slot: 31, slotCategory: "Constrictor", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "T", slot: 1, slotCategory: "missile", designId: 15, shipSymbol: "SHIP_MISSILE", newbRaw: 0 },
  { blueprintSet: "T", slot: 2, slotCategory: "station", designId: 0, shipSymbol: "SHIP_DODO", newbRaw: 64 },
  { blueprintSet: "T", slot: 3, slotCategory: "escape pod", designId: 2, shipSymbol: "SHIP_ESCAPE_POD", newbRaw: 65 },
  { blueprintSet: "T", slot: 4, slotCategory: "cargo", designId: 3, shipSymbol: "SHIP_PLATE", newbRaw: 0 },
  { blueprintSet: "T", slot: 5, slotCategory: "cargo", designId: 4, shipSymbol: "SHIP_CANISTER", newbRaw: 0 },
  { blueprintSet: "T", slot: 6, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "T", slot: 7, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "T", slot: 8, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "T", slot: 9, slotCategory: "shuttle", designId: 36, shipSymbol: "SHIP_SHUTTLE_MK_2", newbRaw: 33 },
  { blueprintSet: "T", slot: 10, slotCategory: "transporter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "T", slot: 11, slotCategory: "trader", designId: 10, shipSymbol: "SHIP_COBRA_MK_3", newbRaw: 160 },
  { blueprintSet: "T", slot: 12, slotCategory: "trader", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "T", slot: 13, slotCategory: "trader", designId: 35, shipSymbol: "SHIP_IGUANA", newbRaw: 160 },
  { blueprintSet: "T", slot: 14, slotCategory: "trader / large carrier", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "T", slot: 15, slotCategory: "small child ship", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "T", slot: 16, slotCategory: "cop", designId: 16, shipSymbol: "SHIP_VIPER", newbRaw: 194 },
  { blueprintSet: "T", slot: 17, slotCategory: "pirate", designId: 19, shipSymbol: "SHIP_KRAIT", newbRaw: 140 },
  { blueprintSet: "T", slot: 18, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "T", slot: 19, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "T", slot: 20, slotCategory: "pirate", designId: 35, shipSymbol: "SHIP_IGUANA", newbRaw: 140 },
  { blueprintSet: "T", slot: 21, slotCategory: "pirate", designId: 10, shipSymbol: "SHIP_COBRA_MK_3", newbRaw: 132 },
  { blueprintSet: "T", slot: 22, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "T", slot: 23, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "T", slot: 24, slotCategory: "pirate", designId: 23, shipSymbol: "SHIP_ASP_MK_2", newbRaw: 140 },
  { blueprintSet: "T", slot: 25, slotCategory: "bounty hunter", designId: 10, shipSymbol: "SHIP_COBRA_MK_3", newbRaw: 130 },
  { blueprintSet: "T", slot: 26, slotCategory: "bounty hunter", designId: 35, shipSymbol: "SHIP_IGUANA", newbRaw: 162 },
  { blueprintSet: "T", slot: 27, slotCategory: "bounty hunter", designId: 23, shipSymbol: "SHIP_ASP_MK_2", newbRaw: 130 },
  { blueprintSet: "T", slot: 28, slotCategory: "bounty hunter", designId: 19, shipSymbol: "SHIP_KRAIT", newbRaw: 162 },
  { blueprintSet: "T", slot: 29, slotCategory: "Thargoid", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "T", slot: 30, slotCategory: "Thargon", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "T", slot: 31, slotCategory: "Constrictor", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "U", slot: 1, slotCategory: "missile", designId: 15, shipSymbol: "SHIP_MISSILE", newbRaw: 0 },
  { blueprintSet: "U", slot: 2, slotCategory: "station", designId: 1, shipSymbol: "SHIP_CORIOLIS", newbRaw: 64 },
  { blueprintSet: "U", slot: 3, slotCategory: "escape pod", designId: 2, shipSymbol: "SHIP_ESCAPE_POD", newbRaw: 65 },
  { blueprintSet: "U", slot: 4, slotCategory: "cargo", designId: 3, shipSymbol: "SHIP_PLATE", newbRaw: 0 },
  { blueprintSet: "U", slot: 5, slotCategory: "cargo", designId: 4, shipSymbol: "SHIP_CANISTER", newbRaw: 0 },
  { blueprintSet: "U", slot: 6, slotCategory: "mining", designId: 5, shipSymbol: "SHIP_BOULDER", newbRaw: 0 },
  { blueprintSet: "U", slot: 7, slotCategory: "mining", designId: 6, shipSymbol: "SHIP_ASTEROID", newbRaw: 0 },
  { blueprintSet: "U", slot: 8, slotCategory: "mining", designId: 7, shipSymbol: "SHIP_SPLINTER", newbRaw: 0 },
  { blueprintSet: "U", slot: 9, slotCategory: "shuttle", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "U", slot: 10, slotCategory: "transporter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "U", slot: 11, slotCategory: "trader", designId: 11, shipSymbol: "SHIP_PYTHON", newbRaw: 160 },
  { blueprintSet: "U", slot: 12, slotCategory: "trader", designId: 37, shipSymbol: "SHIP_CHAMELEON", newbRaw: 161 },
  { blueprintSet: "U", slot: 13, slotCategory: "trader", designId: 32, shipSymbol: "SHIP_GHAVIAL", newbRaw: 160 },
  { blueprintSet: "U", slot: 14, slotCategory: "trader / large carrier", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "U", slot: 15, slotCategory: "small child ship", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "U", slot: 16, slotCategory: "cop", designId: 16, shipSymbol: "SHIP_VIPER", newbRaw: 194 },
  { blueprintSet: "U", slot: 17, slotCategory: "pirate", designId: 19, shipSymbol: "SHIP_KRAIT", newbRaw: 140 },
  { blueprintSet: "U", slot: 18, slotCategory: "pirate", designId: 22, shipSymbol: "SHIP_COBRA_MK_1", newbRaw: 140 },
  { blueprintSet: "U", slot: 19, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "U", slot: 20, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "U", slot: 21, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "U", slot: 22, slotCategory: "pirate", designId: 37, shipSymbol: "SHIP_CHAMELEON", newbRaw: 140 },
  { blueprintSet: "U", slot: 23, slotCategory: "pirate", designId: 11, shipSymbol: "SHIP_PYTHON", newbRaw: 132 },
  { blueprintSet: "U", slot: 24, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "U", slot: 25, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "U", slot: 26, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "U", slot: 27, slotCategory: "bounty hunter", designId: 11, shipSymbol: "SHIP_PYTHON", newbRaw: 130 },
  { blueprintSet: "U", slot: 28, slotCategory: "bounty hunter", designId: 19, shipSymbol: "SHIP_KRAIT", newbRaw: 162 },
  { blueprintSet: "U", slot: 29, slotCategory: "Thargoid", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "U", slot: 30, slotCategory: "Thargon", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "U", slot: 31, slotCategory: "Constrictor", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "V", slot: 1, slotCategory: "missile", designId: 15, shipSymbol: "SHIP_MISSILE", newbRaw: 0 },
  { blueprintSet: "V", slot: 2, slotCategory: "station", designId: 0, shipSymbol: "SHIP_DODO", newbRaw: 64 },
  { blueprintSet: "V", slot: 3, slotCategory: "escape pod", designId: 2, shipSymbol: "SHIP_ESCAPE_POD", newbRaw: 65 },
  { blueprintSet: "V", slot: 4, slotCategory: "cargo", designId: 3, shipSymbol: "SHIP_PLATE", newbRaw: 0 },
  { blueprintSet: "V", slot: 5, slotCategory: "cargo", designId: 4, shipSymbol: "SHIP_CANISTER", newbRaw: 0 },
  { blueprintSet: "V", slot: 6, slotCategory: "mining", designId: 5, shipSymbol: "SHIP_BOULDER", newbRaw: 0 },
  { blueprintSet: "V", slot: 7, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "V", slot: 8, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "V", slot: 9, slotCategory: "shuttle", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "V", slot: 10, slotCategory: "transporter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "V", slot: 11, slotCategory: "trader", designId: 10, shipSymbol: "SHIP_COBRA_MK_3", newbRaw: 160 },
  { blueprintSet: "V", slot: 12, slotCategory: "trader", designId: 12, shipSymbol: "SHIP_BOA", newbRaw: 161 },
  { blueprintSet: "V", slot: 13, slotCategory: "trader", designId: 22, shipSymbol: "SHIP_COBRA_MK_1", newbRaw: 160 },
  { blueprintSet: "V", slot: 14, slotCategory: "trader / large carrier", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "V", slot: 15, slotCategory: "small child ship", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "V", slot: 16, slotCategory: "cop", designId: 16, shipSymbol: "SHIP_VIPER", newbRaw: 194 },
  { blueprintSet: "V", slot: 17, slotCategory: "pirate", designId: 22, shipSymbol: "SHIP_COBRA_MK_1", newbRaw: 140 },
  { blueprintSet: "V", slot: 18, slotCategory: "pirate", designId: 17, shipSymbol: "SHIP_SIDEWINDER", newbRaw: 12 },
  { blueprintSet: "V", slot: 19, slotCategory: "pirate", designId: 20, shipSymbol: "SHIP_ADDER", newbRaw: 132 },
  { blueprintSet: "V", slot: 20, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "V", slot: 21, slotCategory: "pirate", designId: 10, shipSymbol: "SHIP_COBRA_MK_3", newbRaw: 132 },
  { blueprintSet: "V", slot: 22, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "V", slot: 23, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "V", slot: 24, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "V", slot: 25, slotCategory: "bounty hunter", designId: 10, shipSymbol: "SHIP_COBRA_MK_3", newbRaw: 130 },
  { blueprintSet: "V", slot: 26, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "V", slot: 27, slotCategory: "bounty hunter", designId: 22, shipSymbol: "SHIP_COBRA_MK_1", newbRaw: 130 },
  { blueprintSet: "V", slot: 28, slotCategory: "bounty hunter", designId: 17, shipSymbol: "SHIP_SIDEWINDER", newbRaw: 34 },
  { blueprintSet: "V", slot: 29, slotCategory: "Thargoid", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "V", slot: 30, slotCategory: "Thargon", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "V", slot: 31, slotCategory: "Constrictor", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "W", slot: 1, slotCategory: "missile", designId: 15, shipSymbol: "SHIP_MISSILE", newbRaw: 0 },
  { blueprintSet: "W", slot: 2, slotCategory: "station", designId: 1, shipSymbol: "SHIP_CORIOLIS", newbRaw: 64 },
  { blueprintSet: "W", slot: 3, slotCategory: "escape pod", designId: 2, shipSymbol: "SHIP_ESCAPE_POD", newbRaw: 65 },
  { blueprintSet: "W", slot: 4, slotCategory: "cargo", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "W", slot: 5, slotCategory: "cargo", designId: 4, shipSymbol: "SHIP_CANISTER", newbRaw: 0 },
  { blueprintSet: "W", slot: 6, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "W", slot: 7, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "W", slot: 8, slotCategory: "mining", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "W", slot: 9, slotCategory: "shuttle", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "W", slot: 10, slotCategory: "transporter", designId: 9, shipSymbol: "SHIP_TRANSPORTER", newbRaw: 97 },
  { blueprintSet: "W", slot: 11, slotCategory: "trader", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "W", slot: 12, slotCategory: "trader", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "W", slot: 13, slotCategory: "trader", designId: 24, shipSymbol: "SHIP_FER_DE_LANCE", newbRaw: 160 },
  { blueprintSet: "W", slot: 14, slotCategory: "trader / large carrier", designId: 29, shipSymbol: "SHIP_DRAGON", newbRaw: 33 },
  { blueprintSet: "W", slot: 15, slotCategory: "small child ship", designId: 17, shipSymbol: "SHIP_SIDEWINDER", newbRaw: 12 },
  { blueprintSet: "W", slot: 16, slotCategory: "cop", designId: 16, shipSymbol: "SHIP_VIPER", newbRaw: 194 },
  { blueprintSet: "W", slot: 17, slotCategory: "pirate", designId: 17, shipSymbol: "SHIP_SIDEWINDER", newbRaw: 12 },
  { blueprintSet: "W", slot: 18, slotCategory: "pirate", designId: 19, shipSymbol: "SHIP_KRAIT", newbRaw: 140 },
  { blueprintSet: "W", slot: 19, slotCategory: "pirate", designId: 18, shipSymbol: "SHIP_MAMBA", newbRaw: 132 },
  { blueprintSet: "W", slot: 20, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "W", slot: 21, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "W", slot: 22, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "W", slot: 23, slotCategory: "pirate", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "W", slot: 24, slotCategory: "pirate", designId: 24, shipSymbol: "SHIP_FER_DE_LANCE", newbRaw: 140 },
  { blueprintSet: "W", slot: 25, slotCategory: "bounty hunter", designId: 24, shipSymbol: "SHIP_FER_DE_LANCE", newbRaw: 130 },
  { blueprintSet: "W", slot: 26, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "W", slot: 27, slotCategory: "bounty hunter", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "W", slot: 28, slotCategory: "bounty hunter", designId: 17, shipSymbol: "SHIP_SIDEWINDER", newbRaw: 34 },
  { blueprintSet: "W", slot: 29, slotCategory: "Thargoid", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "W", slot: 30, slotCategory: "Thargon", designId: null, shipSymbol: null, newbRaw: 0 },
  { blueprintSet: "W", slot: 31, slotCategory: "Constrictor", designId: null, shipSymbol: null, newbRaw: 0 },
];
